name: b
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  modal_bottom_sheet: ^2.1.2
  flutter_ble_lib: ^2.3.2
  flutter_neumorphic: ^3.2.0
  permission_handler: ^10.2.0
  location: ^4.4.0
  riverpod: ^2.1.1
  pretty_logger: ^1.0.0
  flutter_blue: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true
